#!/usr/bin/with-contenv bash
. /opt/scripts/install.rc;
__check_status;

echo "================================================================================"
echo "Installing YYDecode."
echo "================================================================================"
echo "=== Extracting ..."


cd /yydecode

tar -xzf yydecode-0.2.10.tar.gz
cd yydecode-0.2.10/
./configure
make
sudo make install
make clean
cd ~/
rm -rf /yydecode



echo "--- Done."
hash -r;
echo ""
__exit 0;
